name: secret-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # Lunes 03:00 UTC escaneo semanal

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ''
        with:
          config-path: .gitleaks.toml
          fail: true
      - name: Upload SARIF (optional)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
      - name: Summary
        if: success()
        run: echo "✅ Escaneo de secretos completado sin hallazgos críticos." >> $GITHUB_STEP_SUMMARY
      - name: Summary (detections)
        if: failure()
        run: echo "❌ Se detectaron posibles secretos. Revisar el log de Gitleaks." >> $GITHUB_STEP_SUMMARY
